name: Trigger Sync on Push

on:
  push:
    branches:
      - master

permissions:
  contents: read
  actions: write

jobs:
  dispatch-event:
    runs-on: ubuntu-latest

    steps:
      - name: Send Repository Dispatch Event
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TARGET_REPO: "SWEvenTeam17/SWEvenTeam17.github.io"
          EVENT_TYPE: "sync-folder"

        run: |
          curl -X POST -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer $GITHUB_TOKEN" \
          https://api.github.com/repos/$TARGET_REPO/dispatches \
          -d '{"event_type": "'"$EVENT_TYPE"'"}'

      - name: Check Dispatch Status
        run: echo "Repository Dispatch event sent to $TARGET_REPO"
